### ISSUE TITLE
Use of match() for client-side routing

### ISSUE THREAD

**Issue by nscarlson** [grxy/boilerplate#14]
https://github.com/grxy/boilerplate/blob/4f2e725bb5bd3f2d493b2fd3966185f7544040d1/src/services/client/client.js#L10-L26

- Attempting to use webpack-dev-server breaks, and can't resolve any routes
- `match()` is to be used for server-side routing http://knowbody.github.io/react-router-docs/api/match.html

A [great resource](https://medium.com/@apostolos/server-side-rendering-code-splitting-and-hot-reloading-with-react-router-v4-87239cfc172c#.rmwe3949e) as we continue the discussion on hot-reloading, async routes, client/server routing, code splitting, etc.

**Comment by grxy** [comment]
@nscarlson You have to use match client side when there are routes that are async/have data dependencies. Otherwise, you'd likely have a mismatched checksum between server-side and client-side markup.

**Comment by nscarlson** [comment]
I'll post examples when I get the chance.  Not sure if this is entirely a
webpack-dev-server problem, and can be fixed with a few config parameters.

**Comment by grxy** [comment]
@nscarlson Sweet! Let's definitely discuss.

**Comment by nscarlson** [comment]
Off of latest develop branch, running this command:
`webpack-dev-server --inline --content-base public --history-api-fallback --port 8000`

Results in the following error:

```
/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:365
		throw e;
		^

Error: `output.path` needs to be an absolute path or `/`.
    at Object.setFs (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/lib/Shared.js:88:11)
    at Shared (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/lib/Shared.js:214:8)
    at module.exports (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:22:15)
    at new Server (/usr/local/lib/node_modules/webpack-dev-server/lib/Server.js:56:20)
    at startDevServer (/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:358:12)
    at processOptions (/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:322:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:430:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

Suggest using path.resolve() like so in webpack config:

```
    output: {
        filename: '[name].js',
        libraryTarget: 'umd',
        path: path.resolve(__dirname, './'),
        sourceMapFilename: '[file].map'
    },
```

**Comment by grxy** [comment]
@nscarlson Your latest concern should be resolved in `develop`.

**Comment by grxy** [comment]
@nscarlson Closing this since it is no longer valid with react-router 4.x
